#!groovy
// start

properties([disableConcurrentBuilds()])

pipeline {
    agent any
    environment {
        TARGET_APP_SERVER = 'ec2-3-12-102-248.us-east-2.compute.amazonaws.com'
        JENKINS_USER = 'jenkins'
    }
    tools {
        jdk 'jdk8'
        gradle 'gradle'
    }
    options {
        timestamps()
    }

    stages {
        stage("Checkout") {
            steps {
                checkout(scm: [
                        $class           : 'GitSCM',
                        userRemoteConfigs: [
                                [
                                        url : 'https://github.com/Vadim1984/cloudInAction.git',
                                        name: 'origin'
                                ]
                        ],
                        branches         : [
                                [name: 'refs/heads/master']
                        ]
                ])
            }
        }
        stage('Build') {
            steps {
                echo "Running build: ${env.BUILD_ID}"
                sh 'echo "$GRADLE_OPTS"'
                sh 'gradle clean build --no-daemon -x test'
            }
        }
        stage('Test') {
            steps {
                script {
                    try {
                        sh 'gradle test --no-daemon'
                    } finally {
                        junit '**/build/test-results/test/*.xml'
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                echo 'Testing..'
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}